default: &default

  available_locales:
    - de
    - en
    - ru
    # - alias
  
  # grid, list and/or map
  view_modes:
    - grid

  default_locale: de

  # use 2- or 3-letter country-code
  # have a look at https://github.com/alphabetum/iso-639 for possible methods
  alpha: 'alpha2'
  # alpha: 'alpha3_terminologic'
  
  media_streams:
    defaults:
      video: 480p
      audio: 192k
    video:
      240p: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_sd240p.mp4
      480p: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_sd480p.mp4
      720p: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_sd720p.mp4
    audio:
      128k: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_128k.mp3
      192k: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_192k.mp3
      256k: https://medien.cedis.fu-berlin.de/zwar/zwar/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_256k.mp3

  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interview'
    transcriptor: 'transcript'
    translator: 'translation'
    segmentator: 'segmentation'
    cinematographer: 'cinematographer'
    quality_manager_interviewing: 'quality_manager_interviewing'
    proofreader: 'proofreader' 

  upload_types:
    - bulk_metadata
    - bulk_protocols

  project_name: # Will be used in titles, emails, etc.
    de: 'Zwangsarbeit 1939-1945. Erinnerungen und Geschichte'
    en: 'Forced Labor 1939-1945. Memory and History'
    ru: 'Принудительный труд 1939-1945. Воспоминания и история'

  project_id: 'zwar'

  # used in PDFs
  # give the color code as fractions of 255
  # e.g. '143, 32, 28' ==> '0.560784314, 0.125490196, 0.109803922'
  primary_color_rgb: '0.560784314, 0.125490196, 0.109803922'

  project_shortname: 'ZWAR'

  project_initials: 'ZA' # Use two upper case initials. These will be used for file names, interview id's, etc. So please choose carefully. This cannot be changed later.

  project_domain: 'zwangsarbeit-archiv.de'

  archive_domain: 'archiv.zwangsarbeit-archiv.de'

  project_doi: '10.5072'

  cooperation_partner: "Stiftung 'Erinnerung, Verantwortung und Zukunft'"
  leader: "Apostolopoulos, Nicolas; Pickhan, Gertrud"
  manager: "Tausendfreund, Doris; Pagenstecher, Cord"
  hosting_institution: "Freie Universität Berlin, Universitätsbibliothek/Center für Digitale Systeme"
  funder_names: 
    - "Stiftung 'Erinnerung, Verantwortung und Zukunft'"

  # TODO: Umstellen russ. Links, s. kommentierte Links unten.
  external_links:
    conditions: #nutzungsbedingungen:
      de: 'http://www.zwangsarbeit-archiv.de/sammlung/nutzungsbedingungen/index.html'
      en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/index.html'
      ru: 'http://www.zwangsarbeit-archiv.de/ru/sammlung/nutzungsbedingungen/index.html'
    request_for_use: #nutzungsantrag:
      de: 'http://www.zwangsarbeit-archiv.de/sammlung/nutzungsbedingungen/archivmaterial/index.html'
      en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/archivmaterial/index.html'
      # ru: 'http://www.zwangsarbeit-archiv.de/ru/sammlung/nutzungsbedingungen/archivmaterial/index.html'
    privacy_protection: #datenschutzbestimmungen:
      de: 'http://www.zwangsarbeit-archiv.de/sammlung/nutzungsbedingungen/hinweise_zum_datenschutz/index.html'
      en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/hinweise_zum_datenschutz/index.html'
      ru: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/hinweise_zum_datenschutz/index.html'
    annotation_guidelines:
      de: 'http://www.zwangsarbeit-archiv.de/sammlung/nutzungsbedingungen/anmerkungen-richtlinien/index.html'
      en: 'http://www.zwangsarbeit-archiv.de/en/sammlung/nutzungsbedingungen/anmerkungen-richtlinien/index.html'
      ru: 'http://www.zwangsarbeit-archiv.de/ru/sammlung/nutzungsbedingungen/anmerkungen-richtlinien/index.html'
    team:
      de: 'http://www.zwangsarbeit-archiv.de/team'
      en: 'http://www.zwangsarbeit-archiv.de/en/team'
      #ru: 'http://www.zwangsarbeit-archiv.de/ru/team'
    contact: #kontakt:
      de: 'http://www.zwangsarbeit-archiv.de/kontakt'
      en: 'http://www.zwangsarbeit-archiv.de/en/kontakt'
      ru: 'http://www.zwangsarbeit-archiv.de/ru/kontakt'
    legal_info: #impressum:
      de: 'http://www.zwangsarbeit-archiv.de/impressum'
      en: 'http://www.zwangsarbeit-archiv.de/en/impressum'
      ru: 'http://www.zwangsarbeit-archiv.de/ru/impressum'

  # Please mount the CIFS storage server locally like this (read-only for normal users!):
  # sudo mkdir -p /mnt/eaz-diga.cedis.fu-berlin.de/data
  # /etc/fstab:
  #     //eaz-diga.cedis.fu-berlin.de/data /mnt/eaz-diga.cedis.fu-berlin.de/data cifs noauto,sec=ntlmv2,credentials=/etc/cifs.credentials,uid=root,gid=root,nosetuids,file_mode=0644,dir_mode=0755 0 0
  # /etc/cifs.credentials (create the file with permissions 600 and enter your CIFS credentials)
  #     username=...
  #     password=...
  # If you want to simulate the mount locally you can either place a symlink or mount --bind
  cifs_share: '/mnt/eaz-diga.cedis.fu-berlin.de/data/'

  storage_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup'
  photo_storage_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/bilder'
  archive_management_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/redaktionssystem'
  repository_dir: '/mnt/eaz-diga.cedis.fu-berlin.de/data/archiv_backup/archiv_dis'

  streaming_server: 'rtmpt://stream.cedis.fu-berlin.de/zwangsarbeit-archiv'

  meta_keywords:
    de: 'Speer, Befreiung, Zwangsarbeit, Sklavenarbeit, Geschichte, Nationalsozialismus, Hitler, Sauckel, Oral History, biographisch, Archiv, Gedenken, Literatur, Quellen, Interviews, Erinnerungen, Stimmen, Fotografien, Entschädigung, Konzentrationslager, KZ, Ukrainerinnen, Tschechen, Polen, Ostarbeiter, Ostarbeiterinnen, Stiftung EVZ, audiovisuelle Archive, multimedial, Inventarisierung, Museum, Universität, Digitalisierung, Segmentierung, Übersetzung, STO, IMI, Militärinternierte, Auschwitz, Buchenwald, Flossenbürg, Zigeuner, Roma, Sinti, Displaced Person, Zwangsarbeiterlager, Zweiter Weltkrieg, Drittes Reich, 1939, 1940, 1941, 1942, 1943, 1944, 1945, Ghetto, Arbeitserziehungslager, Vernichtung, Verfolgung, Widerstand, Litauen, Moldawien, Ukraine, Polen, Italien, Norwegen, vergessene Opfer, Kriegskinder, Germanisierung, Deportation, Platoprojekt, Alexander von Plato, Fernuniversität, Hitlers Sklaven, SS, Gestapo, Wehrmacht'
    en: 'audiovisual oral history archive, forced labor, 1939-1945, 3rd Reich'
    ru: '##ru##'

  contact_email: 'mail@zwangsarbeit-archiv.de'

  smtp_server: 'mail.fu-berlin.de'

  # Interview partner properties usually depend on the historical context and must therefore be configured
  # on a per-project basis:
  # - To create a property from sub-entries of a registry entry, use the (default language) descriptor to identify the
  #   entry. The ID of the property will define the internal property name.
  # - To create a property from references of a certain reference type, use the registry reference code
  #   as ID. The clear name will be retrieved from the registry reference type table.
  # - Interview partner properties will be used as search facets when setting the facet property to 'true'. The order of
  #   entries is significant to determine in which order entries appear in the "search facet" section.
  # NB: Only properties from a 'registry entry' or 'registry reference type' source can be used as facet entries.

  metadata_fields:
    - name: 'person_reference'
      source: 'registry_entry'
    - name: 'forced_labor_groups'
      source: 'registry_entry'
      use_as_facet: true
      display_on_landing_page: true`
    - name: 'forced_labor_fields'
      source: 'registry_entry'
      use_as_facet: true
    - name: 'language_id'
      source: 'language'
      use_as_facet: true
    - name: 'year_of_birth'
      source: 'person'
      use_as_facet: true
    - name: 'gender'
      source: 'person'
      use_as_facet: true
      values:
        female: 'female'
        male: 'male'
        diverse: 'diverse'
    - name: 'collection_id'
      source: 'collection'
      use_as_facet: true 
    - name: 'media_type'
      source: 'interview'
      use_as_facet: true
    - name: 'birth_location'
      source: 'registry_reference_type'
      use_as_facet: false
      display_on_landing_page: false
    - name: 'forced_labor_habitations'
      source: 'registry_entry'
      # use_as_facet: true
    - name: 'home_location'
      source: 'registry_reference_type'
      use_as_facet: false
    - name: 'forced_labor_location'
      source: 'registry_reference_type'
      use_as_facet: false
    - name: 'deportation_location'
      source: 'registry_reference_type'
      use_as_facet: false
    - name: 'return_location'
      source: 'registry_reference_type'
      use_as_facet: false

  # NB: The map has not yet been generalized to work for all historical
  # contexts. It relies on ZWAR-specific registry data structures (i.e. a
  # three-level location hierarchy, companies, camps and specific registry
  # reference types like "forced labor locations").
  # If you want to use the map for a different historical context then a
  # generic map will have to be specified by the project responsibles first.
  # Therefore set this to "false" for all projects except ZWAR unless
  # you also change the corresponding map code.
  uses_map: true

  has_newsletter: true

  hidden_registry_entry_ids:
    - 28205
    - 28221
    - 28237

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

