development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: ohd_development
  pool: 5
  username: root
  password: rootpassword
  host: db
  variables:
    foreign_key_checks: 0

test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: ohd_test
  pool: 5
  username: root
  password: rootpassword
  host: db
  variables:
    foreign_key_checks: 0