development:
  #adapter: async
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://redis:6379/0') %>

production:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://redis:6379/0') %>
