development:
  prefix: <%= ENV.fetch('DATACITE_PREFIX_DEVELOPMENT', '10.5072') %>
  client_id: <%= ENV.fetch('DATACITE_CLIENT_ID_DEVELOPMENT', 'TIB.FUB') %>
  password: <%= ENV.fetch('DATACITE_PASSWORD_DEVELOPMENT', 'Epub_test!') %>
  url: <%= ENV.fetch('DATACITE_URL_DEVELOPMENT', 'https://api.test.datacite.org/dois') %>

test:
  prefix: <%= ENV.fetch('DATACITE_PREFIX_TEST', '10.5072') %>
  client_id: <%= ENV.fetch('DATACITE_CLIENT_ID_TEST', 'TIB.FUB') %>
  password: <%= ENV.fetch('DATACITE_PASSWORD_TEST', 'Epub_test!') %>
  url: <%= ENV.fetch('DATACITE_URL_TEST', 'https://api.test.datacite.org/dois') %>

staging:
  prefix: <%= ENV.fetch('DATACITE_PREFIX_STAGING', '10.17169') %>
  client_id: <%= ENV['DATACITE_CLIENT_ID_STAGING'] %>
  password: <%= ENV['DATACITE_PASSWORD_STAGING'] %>
  url: <%= ENV.fetch('DATACITE_URL_STAGING', 'https://api.datacite.org/dois') %>

production:
  prefix: <%= ENV.fetch('DATACITE_PREFIX_PRODUCTION', '10.17169') %>
  client_id: <%= ENV['DATACITE_CLIENT_ID_PRODUCTION'] %>
  password: <%= ENV['DATACITE_PASSWORD_PRODUCTION'] %>
  url: <%= ENV.fetch('DATACITE_URL_PRODUCTION', 'https://api.datacite.org/dois') %>
