servers:
  web:
    - 160.45.152.195

proxy:
  ssl: true
  host: avd-test.ub.fu-berlin.de
  app_port: 3000

volumes:
  - "/home/avd1/avd/storage/app-cache:/app/tmp/cache"
  - "/home/avd1/avd/storage/app-files:/app/tmp/files"
  - "/home/avd1/avd/storage/app-logs:/app/log"

ssh:
  user: avd1

accessories:
  db:
    image: mariadb:10.5
    hosts:
      - 160.45.152.195
    env:
      clear:
        MYSQL_HOST_PRODUCTION: '%'
      secret:
        - MYSQL_PASSWORD_PRODUCTION
    directories:
      - data:/var/lib/mysql

  solr:
    image: solr:5.5
    hosts:
      - 160.45.152.195
    directories:
      - solr_data:/opt/solr/server/solr/mycores
