dev:
  service: Disk
  root: <%= Rails.root.join("storage") %>

fu_server:
  service: Disk
  root: /mnt/vfiler11.campus.fu-berlin.de/cedis_stream04_da/ohd/storage
  # new trove production path:
  #root: /mnt/trove.storage.fu-berlin.de/ohd-av/ohd_assets/production
  # new trove staging path:
  #root: /mnt/trove.storage.fu-berlin.de/ohd-av/ohd_assets/staging

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: ''
  secret_access_key: ''
