dev:
  service: Disk
  root: <%= ENV.fetch('STORAGE_DEV_ROOT', Rails.root.join('storage')) %>

test:
  service: Disk
  root: <%= ENV.fetch('STORAGE_TEST_ROOT', Rails.root.join('tmp/storage')) %>

staging:
  service: Disk
  root: <%= ENV.fetch('STORAGE_STAGING_ROOT', '/mnt/vfiler11.campus.fu-berlin.de/cedis_stream04_da/ohd/storage') %>

prod:
  service: Disk
  root: <%= ENV.fetch('STORAGE_PROD_ROOT', '/mnt/vfiler11.campus.fu-berlin.de/cedis_stream04_da/ohd/storage') %>
