development:
  solr:
    hostname: <%= ENV.fetch('SOLR_HOST_DEVELOPMENT', ENV.fetch('SOLR_HOST', 'solr')) %>
    port: <%= ENV.fetch('SOLR_PORT_DEVELOPMENT', ENV.fetch('SOLR_PORT', '8983')) %>
    log_level: <%= ENV.fetch('SOLR_LOG_LEVEL_DEVELOPMENT', 'INFO') %>
    path: <%= ENV.fetch('SOLR_PATH_DEVELOPMENT', '/solr/default') %>

test:
  solr:
    hostname: <%= ENV.fetch('SOLR_HOST_TEST', 'localhost') %>
    port: <%= ENV.fetch('SOLR_PORT_TEST', '8983') %>
    log_level: <%= ENV.fetch('SOLR_LOG_LEVEL_TEST', 'INFO') %>
    path: <%= ENV.fetch('SOLR_PATH_TEST', '/solr/default') %>

staging:
  auto_commit_after_request: <%= ENV.fetch('SOLR_AUTO_COMMIT_AFTER_REQUEST_STAGING', ENV.fetch('SOLR_AUTO_COMMIT_AFTER_REQUEST', 'true')) == 'true' %>
  auto_commit_after_delete_request: <%= ENV.fetch('SOLR_AUTO_COMMIT_AFTER_DELETE_REQUEST_STAGING', ENV.fetch('SOLR_AUTO_COMMIT_AFTER_DELETE_REQUEST', 'true')) == 'true' %>
  solr:
    hostname: <%= ENV.fetch('SOLR_HOST_STAGING', ENV.fetch('SOLR_HOST', 'localhost')) %>
    port: <%= ENV.fetch('SOLR_PORT_STAGING', ENV.fetch('SOLR_PORT', '8983')) %>
    log_level: <%= ENV.fetch('SOLR_LOG_LEVEL_STAGING', 'WARNING') %>
    path: <%= ENV.fetch('SOLR_PATH_STAGING', '/solr/production') %>

production:
  auto_commit_after_request: <%= ENV.fetch('SOLR_AUTO_COMMIT_AFTER_REQUEST_PRODUCTION', ENV.fetch('SOLR_AUTO_COMMIT_AFTER_REQUEST', 'true')) == 'true' %>
  auto_commit_after_delete_request: <%= ENV.fetch('SOLR_AUTO_COMMIT_AFTER_DELETE_REQUEST_PRODUCTION', ENV.fetch('SOLR_AUTO_COMMIT_AFTER_DELETE_REQUEST', 'true')) == 'true' %>
  solr:
    hostname: <%= ENV.fetch('SOLR_HOST_PRODUCTION', ENV.fetch('SOLR_HOST', 'localhost')) %>
    port: <%= ENV.fetch('SOLR_PORT_PRODUCTION', ENV.fetch('SOLR_PORT', '8983')) %>
    log_level: <%= ENV.fetch('SOLR_LOG_LEVEL_PRODUCTION', 'WARNING') %>
    path: <%= ENV.fetch('SOLR_PATH_PRODUCTION', '/solr/production') %>
