---
:still:
  media_type: 'still'
  path: 'https://media.oral-history.digital/SHORTNAME/INTERVIEW_ID/INTERVIEW_ID.jpg'
:audio_hls:
  media_type: 'audio'
  path: 'https://media.oral-history.digital/SHORTNAME/INTERVIEW_ID/INTERVIEW_ID_TAPE_COUNT_TAPE_NUMBER/INTERVIEW_ID_TAPE_COUNT_TAPE_NUMBER.m3u8'
  resolution: 'hls'
:video_hls:
  media_type: 'video'
  path: 'https://media.oral-history.digital/SHORTNAME/INTERVIEW_ID/INTERVIEW_ID_TAPE_COUNT_TAPE_NUMBER/INTERVIEW_ID_TAPE_COUNT_TAPE_NUMBER.m3u8'
  resolution: 'hls'
